# EL MÉTODO K-MEANS

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)

In [3]:
data

array([[0.75469865, 0.69381347, 0.57322157],
       [0.36659115, 0.44780359, 0.62412276],
       [0.20436113, 0.85137581, 0.00396488],
       [0.50554137, 0.22517778, 0.48803617],
       [0.64662183, 0.51888014, 0.42731601],
       [0.52677313, 0.51215839, 0.79858013],
       [0.05330659, 0.57397133, 0.4218885 ],
       [0.44913257, 0.83743219, 0.98993902],
       [0.68474064, 0.80332356, 0.75874544],
       [0.77986915, 0.40135223, 0.61668232],
       [0.57470396, 0.68640756, 0.60171653],
       [0.55409106, 0.5374147 , 0.57030792],
       [0.21991806, 0.04423368, 0.33667296],
       [0.0596798 , 0.24301892, 0.3670054 ],
       [0.12390784, 0.31137133, 0.07098834],
       [0.9984851 , 0.03206848, 0.88717499],
       [0.06068288, 0.81112703, 0.8931389 ],
       [0.5033285 , 0.98956601, 0.95793146],
       [0.2424746 , 0.51802381, 0.95735229],
       [0.68634145, 0.78814339, 0.05400411],
       [0.37020486, 0.5753005 , 0.83211063],
       [0.67245113, 0.79977193, 0.63799106],
       [0.

In [6]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.57470396, 0.68640756, 0.60171653],
       [0.12390784, 0.31137133, 0.07098834]])

In [7]:
from scipy.cluster.vq import vq

In [8]:
vq(data, clust_centers)

(array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0]),
 array([0.18238667, 0.31740327, 0.55006338, 0.48004124, 0.25229577,
        0.26723662, 0.44393042, 0.43507852, 0.2245785 , 0.3515299 ,
        0.        , 0.15365632, 0.38880433, 0.31052116, 0.        ,
        0.83020276, 0.60390365, 0.47316866, 0.51498177, 0.56815668,
        0.32748451, 0.15401893, 0.16656478, 0.54545946, 0.34212041,
        0.52363168, 0.4143979 , 0.32799008, 0.60621326, 0.6586932 ]))

In [9]:
from scipy.cluster.vq import kmeans

In [10]:
kmeans(data, clust_centers)

(array([[0.51389277, 0.54323439, 0.69475095],
        [0.26736967, 0.51415748, 0.16711225]]),
 0.35843801683445)

In [11]:
kmeans(data, 2)

(array([[0.51389277, 0.54323439, 0.69475095],
        [0.26736967, 0.51415748, 0.16711225]]),
 0.35843801683445)